# Generated by Django 4.1.5 on 2023-11-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monster_author_comment_survivor_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivors', to='core.profile'),
        ),
    ]
