# Generated by Django 4.1.5 on 2023-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_monster_author_alter_survivor_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['id'], 'verbose_name': 'Monster', 'verbose_name_plural': 'Monsters'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='survivor',
            options={'ordering': ['id'], 'verbose_name': 'Survivor', 'verbose_name_plural': 'Survivors'},
        ),
        migrations.AlterField(
            model_name='monster',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/monsters/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/survivors/%Y/%m/%d/'),
        ),
    ]
