# Generated by Django 4.1.5 on 2023-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_monster_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='monsters/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='survivors/%Y/%m/%d/'),
        ),
    ]
