# Generated by Django 4.1.5 on 2023-12-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_monster_cover_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Monster', 'verbose_name_plural': 'Monsters'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='survivor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survivor', 'verbose_name_plural': 'Survivors'},
        ),
    ]
